version: '3.8'

services:
  truenas-mcp:
    build: .
    image: truenas-mcp-server:latest
    volumes:
      # Mount docs as read-only to ensure container doesn't modify them
      - ./docs:/app/docs:ro
    # Required for MCP stdio communication
    stdin_open: true
    tty: true
    # Ensure clean shutdown
    stop_signal: SIGTERM
    stop_grace_period: 10s

  truenas-mcp-test:
    build: .
    image: truenas-mcp-server:latest
    volumes:
      # Mount docs as read-only for tests
      - ./docs:/app/docs:ro
      # Mount source code for live testing during development
      - ./truenas_mcp_server.py:/app/truenas_mcp_server.py:ro
      - ./truenas_mcp_tools_server.py:/app/truenas_mcp_tools_server.py:ro
      - ./tests:/app/tests:ro
      - ./pytest.ini:/app/pytest.ini:ro
    command: pytest
    # Ensure clean shutdown
    stop_signal: SIGTERM
    stop_grace_period: 10s